AWSTemplateFormatVersion: "2010-09-09"

Description: Application Instance Template

Metadata:
  Comment: "
  List of mandatory tags to set in the stack creation wizard:
    - Env:
        Description: The name of the environment being deployed to.
        Type: String
        Default: dev
        AllowedValues: dev, test, prod
    - Appname:
        Description: The name of the application being deployed.
        Type: String
  "

Parameters:
  Env:
    Description: The name of the environment being deployed to.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
  Appname:
    Description: The name of the application being deployed.
    Type: String

  AppServersSize:
    Description: Frontend Server instance type
    Type: String
    Default: t3.large
    AllowedValues:
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m4.16xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - c5.18xlarge
      - r4.large
      - r4.xlarge
      - r4.2xlarge
      - r4.4xlarge
      - r4.8xlarge
      - r4.16xlarge

  VPCId:
    Description: "VCP Id"
    Type: AWS::EC2::VPC::Id

  AppSubnet1:
    Description: "Subnet ID of the Frontend Server 1"
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0a450499ffc8c03d8

  AppServer1AMI:
    Description: AMI ID for Frontend instance 1
    Type: AWS::EC2::Image::Id
    Default: ami-080955706b2720e22

Resources:
  AppServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow connection to the application
      VpcId:
        Ref: VPCId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  AppServer1:
    Type: "AWS::EC2::Instance"
    Properties:
      BlockDeviceMappings:
        -
          DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 100
            VolumeType: gp2
            DeleteOnTermination: true
      ImageId:
        Ref: AppServer1AMI
      InstanceType:
        Ref: AppServersSize
      Monitoring: true
      IamInstanceProfile: !Join
        - '-'
        - - Ref: Env
          - Ref: Appname
          - 'app-ec2-role'
      SubnetId:
        Ref: AppSubnet1
      SecurityGroups:
        - Ref: AppServerSG
      Tags:
        - Key: Name
          Value: !Ref Appname
        - Key: Env
          Value: !Ref Env
        - Key: Appname
          Value: !Ref Appname 

  DataDisk: 
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone: !GetAtt AppServer1.AvailabilityZone
      Size : 100
      Encrypted: true
      VolumeType: gp2
      Tags:
          - Key: Name
            Value: !Ref Appname
          - Key: Env
            Value: !Ref Env
          - Key: Appname
            Value: !Ref Appname
              
  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref AppServer1
      VolumeId: !Ref DataDisk
      Device: /dev/sdh