AWSTemplateFormatVersion: 2010-09-09
Description: Configure the AWSJenkinsAdministrationRole to enable use of AWS CloudFormation in Jenkins.

Resources:
  AdministrationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: AWSJenkinsAdministrationRole
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - 
          PolicyName: "AWSJenkinsAdministrationRole"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: "*"
                Resource: "*"
            
  JenkinsServerRole:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: '/'
      Roles:
        - Ref: AdministrationRole
      InstanceProfileName: jenkins-admin-role